"""empty message

Revision ID: 05b8ab1b8d7b
Revises: f1b3e2b1d4dc
Create Date: 2024-10-04 21:38:57.171152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b8ab1b8d7b'
down_revision = 'f1b3e2b1d4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['filename'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
