"""empty message

Revision ID: b87364663364
Revises: 05b8ab1b8d7b
Create Date: 2024-10-04 23:39:17.966343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b87364663364'
down_revision = '05b8ab1b8d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index('_filename')
        batch_op.drop_column('_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index('_filename', ['_filename'], unique=False)

    # ### end Alembic commands ###
