"""empty message

Revision ID: ed3352df74f6
Revises: 59f23134b5b2
Create Date: 2024-08-06 14:17:49.249059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3352df74f6'
down_revision = '59f23134b5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=700), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
