"""empty message

Revision ID: f1b3e2b1d4dc
Revises: ed3352df74f6
Create Date: 2024-08-07 20:44:05.088245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b3e2b1d4dc'
down_revision = 'ed3352df74f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reject_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checked_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('checked_items')
        batch_op.drop_column('reject_status')

    # ### end Alembic commands ###
